### ISSUE TITLE
重构中间件部分

### ISSUE THREAD

**Issue by demohi** [larkjs/lark#100]
随着中间件使用的越来越多，导致代码非常混乱，用户无法直观的看出 lark 使用了哪些中间件、中间件的使用顺序、如何配置中间件

参考 kraken、loopback、sailjs 等企业级框架，改用配置的方式重构

**Comment by zezhou** [comment]
给个更详细的方案，大家来讨论下

**Comment by zezhou** [comment]
经讨论先搁置该意见
