### ISSUE TITLE
部分代码中写死了执行文件为node，因此iojs会报错

### ISSUE THREAD

**Issue by viRingbells** [larkjs/lark#140]
如bin/lark中，写死了node。
同时，bootstrap中，为了保证调起PM2时PATH中有node，也进行了强制验证。
虽然没有通过代码验证（PM2的代码太难读了），不过确认了使用iojs来执行lark启动PM2时，会报错。。

考虑到iojs最终应该会合并到nodejs上，此issue不一定会修。不过需要知道的是现在使用iojs来执行lark，是有问题的。

**Comment by zezhou** [comment]
greate, let's wait for the merge of node.js and io.js
