### ISSUE TITLE
Websocket Module

### ISSUE THREAD

**Issue by Dillybob92** [larkjs/lark#142]
Hey, concerning your module here:
https://www.npmjs.com/package/lark-websocket

inside client.js at line 120:

client._socket.on('close',function(){
         console.log(client);
        clearInterval(inter);
        client.emit('close', client);
    });

We need to somehow remove that client object after each time someone closes a connection, or that object becomes a memory leak in nodejs.  I was wondering if you can help me accomplish this, love your module and it's very lightweight as compared to the ws module on github, I love it.

Thanks,

Nick

**Comment by viRingbells** [comment]
Thanks for your information Nick.

It seems client's listeners are the cause. When the client is closed, its listeners are not removed. 
These listeners usually hold the client, which in turn prevents the client from being removed.

I have fixed this problem by removing all listeners when client closed.
Hopes this would help you ^_^

**Comment by zezhou** [comment]
Here is commit: https://github.com/larkjs/lark-websocket/commit/e2c2c5585bc9c43a40aea39deaedd23d941c22d0

**Comment by Dillybob92** [comment]
I think the V8 garbage collector will eventually remove the listeners I am talking about the data inside the socket object itself ( the properties inside the object are floating in memory ).
I'll give this  a shot when I get home from school, thank you very much!
