### ISSUE TITLE
入门教程bug

### ISSUE THREAD

**Issue by levone911** [larkjs/lark#146]
其中“编写 demo 的业务逻辑”
第二步：``
lark create pageService index
``
终端中执行没有任何提示信息。项目里也并没有新建index.js文件，请教。

**Comment by viRingbells** [comment]
抱歉文档方面目前有些滞后，
lark create controller  demo.js
lark create page  demo
lark create data demo
lark create dao demo
使用这几个命令。

**Comment by viRingbells** [comment]
文档已经更新，虽然详细介绍方面还未完成，不过hello world示例已经修改完毕。

**Comment by levone911** [comment]
非常🙏

**Comment by zezhou** [comment]
lark 还在变化中，1.0版后会比较稳定，预计 本月会做到1.0
