### ISSUE TITLE
路由处理bug

### ISSUE THREAD

**Issue by levone911** [larkjs/lark#150]
其中 “参数匹配”  部分
``
router.get('/hello/:name', function * (next) {    // ===> GET /hello/{name}  {name}是不含'/'的字符串
  var name = this.params.name;
});
``
``
router.get('/foo/*bar', function * (next) {       // ===> GET /foo/{bar}     {bar}是任意字符串
  var bar  = this.params.bar;
});
``
第二种获取方法 /* 方式无法获取， /: 方式是可以的。

/*获取
![184c8313-918d-4c28-a3b0-de957cbc19cd](https://cloud.githubusercontent.com/assets/3076876/8477333/de4ce32a-20fb-11e5-9a66-b0f659101707.png)

/: 获取
![a2886a74-db4e-4375-acd3-3d48ead8d40e](https://cloud.githubusercontent.com/assets/3076876/8477353/06f0fa28-20fc-11e5-9124-53394be02a17.png)

**Comment by zezhou** [comment]
我记忆中第二种方式匹配的和第一种是有区别的

对于 /about/about/foo

/about/:name/foo 中的 name 匹配的是about

/about/*name 中的name 匹配的剩下的所有的url about/foo

也就是说明文档这块是有问题的。

待我实际跑一下，补充跑的结果上来

**Comment by viRingbells** [comment]
我看了一下，我们使用的是koa-router，并非tj写的koa-route，规则与express的router规则不太一样…不过koa-route的下载数和star的数量也不是很多，看看我们有没有必要换成koa-route?

**Comment by zezhou** [comment]
纳尼。。。我们用了一个山寨 router?

**Comment by demohi** [comment]
koa-router并非山寨，而是一个功能更强大的router   下载量也远超koa-route(这个只是一个官方的demo库)，koa-route也在自己的reademe中推荐koa-router If you need a full-featured solution check out koa-router, a Koa clone of express-resource.

**Comment by demohi** [comment]
@levone911    lark的路由是基于https://github.com/alexmingoia/koa-router   更详细的使用文档，可以去koa-router查看

**Comment by levone911** [comment]
好的，🙏各位

**Comment by zezhou** [comment]
这里应该是我们的文档写错了
 
    router.get('/foo/*bar'

上面这种方式是错误的，正确的是下面这种

    router.get('/foo/:bar*'

我看了下源码,lark-router 和 express 用的都是 path-to-RegExp 组件来解析url的，支持的正则应该是一样的。我又看了下express的文档，跑了下代码，确定如下代码是可以跑通的。

    .get('/:bar*', function * (next){
        this.body = this.params.bar                                                                                                                                                                    
        yield next
    })

输入url `http://localhost:8888/about/about/hello/P001` 后，会返回匹配的bar参数`about/about/hello/P001`

因此确定是我们的文档写错了。

我来把文档修改正确。多些@levone911
