### ISSUE TITLE
lark 命令行中获取绝对路径代码优化

### ISSUE THREAD

**Issue by zezhou** [larkjs/lark#151]
lark 命令行中有一段代码获取绝对路径
我找到了这个 module, 可以更优雅获取绝对路径
https://www.npmjs.com/package/app-root-path
这块应该可以优化下

**Comment by viRingbells** [comment]
我认为app-path-root获取路径的方式对于lark来并不能胜任所有的情况。
在全局安装的情况下，这个module的机制是：`path.dirname(require.main.filename);` ，那么实际是返回的lark文件自身所在的目录，而非app所在的目录。这是最主要的一个问题。
另外，在非全局的情况下，app-root-path的机制是： `path.resolve(__dirname).split('/node_modules')[0];` 
在某些不是很规范的使用情况下，例如，app的目录是_xxx/nodel_modules/yyy/zz/app_，或者lark并不是安装在_app/node_modules_中，而是_app/../node_modules_中，app-root-path的返回结构都不会符合我们的需要。
不知道有没有更加完善的解决方案。

**Comment by zezhou** [comment]
按lark 放 app/node_modules/lark 的默认情况下
app-path-root 放 lark的 peer-dependence 而不是dependence下面，是不是就能返回正确的app路径了

**Comment by viRingbells** [comment]
不好解决全局安装的问题，
`npm install -g lark` 后，直接敲 `lark` 命令，执行的是_/usr/local/..._里面的lark，只有 `./bin/lark` 会执行_app/node_modules/.bin/lark_ 。

**Comment by zezhou** [comment]
那可不可以这样
假设在/home/work/demo目录下
全局安装后，敲lark命令，先获得执行lark命令的路径 /home/work/demo, 然后去 node_modules里找 app-path-root,如果没有找到，再向上遍历，如果能找到就能确定根目录，直到找到或退出。

**Comment by zezhou** [comment]
process.cwd() 能拿到当前路径
