### ISSUE TITLE
没有用lark new 创建项目配置时，lark-mvc ignore的错误

### ISSUE THREAD

**Issue by zezhou** [larkjs/lark#153]
错误日志为
> lark-demo/node_modules/lark/node_modules/lark-mvc/index.js:22
>    options.ignore = options.ignore || 'helper';

options.ignore 这块逻辑需要优化
另外这块后续要大动刀，把自动加载逻辑去掉，使业务变简单

**Comment by viRingbells** [comment]
改吧改吧，之前设计的API层，结果就没有实现。。
最好能自定义分层，包括分那几层，每一层的名字和层层之间上下关系都能灵活制定。
不过，这部分大改之后，lark命令相关的generator也要大改，可能会是个坑。

**Comment by zezhou** [comment]
fiex in https://github.com/larkjs/lark-mvc/commit/35d4aa65a872b45e4a49329ea23932ad20a5b13f
