### ISSUE TITLE
热重载模式

### ISSUE THREAD

**Issue by zezhou** [larkjs/lark#161]
aotu-refresh 模式
在debug模式下，当前端代码和node.js代码更新时，自动重启服务。

**Comment by zezhou** [comment]
generate-lark 里生成的项目里的Gruntfile.js已配置了热重载功能。
本次更新计划理顺下这个功能，整理一篇wiki，并且将 lark run 集成进这个功能。

**Comment by viRingbells** [comment]
试试lark watch ?
