### ISSUE TITLE
Lark 项目大小精简

### ISSUE THREAD

**Issue by viRingbells** [larkjs/lark#163]
现在用npm intall的Lark，一共有183M，有点儿太大了，会导致npm install特别耗时，而且实际生产中的项目也会因为目录过大而超时。
Lark的大头是generator-lark，因为yeoman-generator有122M，然后是lark-bootstrap有21M。
其他的加起来也有60M，看看能不能用peerDependency的方式精简一下

**Comment by zezhou** [comment]
项目里加 .npmignore 可以把 test 和 example 从 npm 里清除掉

**Comment by zezhou** [comment]
上线项目中有些 develop 的功能在线上环境是不需要的，比如 generator-lark，看看怎么在线上版本中精简

**Comment by zezhou** [comment]
lark new 会重新装 lark, 看能不能从已有的copy

**Comment by viRingbells** [comment]
generator已经升级，现在会优先拷贝require.resolve('lark')
