### ISSUE TITLE
检查 NODE_ENV  参数在 production 环境下是否正确

### ISSUE THREAD

**Issue by zezhou** [larkjs/lark#164]
根据这篇文章的内容 http://apmblog.dynatrace.com/2015/07/22/the-drastic-effects-of-omitting-node_env-in-your-express-js-applications/ ，koa, express 等框架 在没有设置 NODE_ENV 环境变量的情况会默认设置环境变量为 development, 导致性能下降严重。因此需要检测该项环境变量设置在 lark 的各项 production 环境下是否正确。

**Comment by zezhou** [comment]
产出：改动前后性能对比；将相关内容更新到 wiki 上 https://github.com/larkjs/lark/wiki/%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE 的相关内容里。

**Comment by jabez128** [comment]
> 需要检测该项环境变量设置在 lark 的各项 production 环境下是否正确。

我理解是不是只需要在application.js文件中添加

      process.env.NODE_ENV = "production"

即可？

**Comment by zezhou** [comment]
你说的方法我没有测试过。我说一种测试过的方法：调用 node js 命令时设置环境变量即可。
比如之前启动命令是 

> lark start

里面调用的命令是

> node --harmony index.js

现在把里面调用的命令改为

> NODE_ENV="production" node --harmony index.js

就好了

**Comment by viRingbells** [comment]
```
if (program.environment) {
    cmd += 'NODE_ENV=' + program.environment;
}
else if(default_env){
    cmd += 'NODE_ENV=' + default_env;
}
cmd += ' ' + process.execPath + ' ' + process.execArgv.join(" ") + ' index.js ' + _cmd;
```
这个是lark-commands中的代码，如果是通过lark启动的，那就应该设置了NODE_ENV的值

**Comment by jabez128** [comment]
我看了下这个[回答](http://stackoverflow.com/questions/9198310/how-to-set-node-env-to-production-development-in-os-x)，感觉设置`process.env`的方法比较方便

**Comment by zezhou** [comment]
设置 process.env 的会覆盖其它设置么
比如设置了这个后，如果我按 NODE_ENV 设置 development 环境，会不会不生效

**Comment by jabez128** [comment]
@zezhou 有道理

**Comment by jabez128** [comment]
增加了对于NODE_ENV的判断，如果没有进行配置，默认情况使用production。
benchmark等待lark-commands模块问题修复以后进行测试。
