### ISSUE TITLE
无法POST图片

### ISSUE THREAD

**Issue by viRingbells** [larkjs/lark#172]
现在Lark所用的bodyparser是[koa-bodyparser](https://www.npmjs.com/package/koa-bodyparser)；根据[这个issue](https://github.com/koajs/bodyparser/issues/4)来看，这个库只支持`json`和`urlencoded`的，所以导致POST图片（以及一些其他类型的数据）时，会报错。

需要增加对其他格式的支持。

**Comment by viRingbells** [comment]
参考：[koala body-parsing](https://github.com/koajs/koala/blob/master/docs/body-parsing.md)

**Comment by zezhou** [comment]
Should this issue be closed now?
