### ISSUE TITLE
lark 命令行详细设计

### ISSUE THREAD

**Issue by demohi** [larkjs/lark#29]
## lark 命令行工具介绍
lark 命令行是一个为了协助快速开发  lark 项目而创建的项目，您可以通过 lark 命令 快速创建项目、开发热重启、开发测试以及开发完之后打包发布的一整套从创建、开发到部署的方案。

## lark 命令行安装
```bash
$ npm install lark -g
```
## lark 命令
lark is a tool for managing lark app.

Usage:

    lark command [arguments]

The commands are:

    -h, --help     output usage information
    -V, --version  output the version number
    n, new         create an application base on lark framework
    a, api         create an api application base on lark framework
    g, generate    source code generator
    r, run         run the lark app in development
    s, start       run the lark app in production

### new 命令
new 命令是新建一个 Web 项目，我们在命令行下执行 lark new <项目名> 创建一个新的项目。但是注意当前目录下不能存在和项目名相同的文件夹

```bash
$ lark new lark-web-demo

```

### api 命令

```bash
$ lark api lark-api-demo
```

### run 命令
由于 Node.js 的运行机制，每一次我们修改代码，都要去手动重启项目。run 命令会监听文件的变化，当发现文件更新，会自动重启。用来开发时使用。

```bash
$ lark run
```

### start 命令

start 命令是对 pm2命令的封装，用来在线上使用，会默认开启cluster模式

### generate 命令
包含 controller、api、model、pageservice、dataservice

``` bash
# 根据路由生成对应目录以及 js
$ lark generate controller user/list
# 生成restapi
$ lark generate rest user
# 生成 pageservice
$ lark generate pageservice user
# 生成 model
$ lark generate model user
```

## lark 命令行依赖库
lark 命令行解析基于 [command.js](https://github.com/tj/commander.js)开发。commandjs非常灵活，很方便开发复杂的命令行工具，另外还可以提供自动的 help 命令生成

```javascript
var program = require('commander');

program
  .version('0.0.1')
  .option('-C, --chdir <path>', 'change the working directory')
  .option('-c, --config <path>', 'set config path. defaults to ./deploy.conf')
  .option('-T, --no-tests', 'ignore test hook')


program
  .command('exec <cmd>')
  .alias('ex')
  .description('execute the given remote cmd')
  .option("-e, --exec_mode <mode>", "Which exec mode to use")
  .action(function(cmd, options){
    console.log('exec "%s" using %s mode', cmd, options.exec_mode);
  }).on('--help', function() {
    console.log('  Examples:');
    console.log();
    console.log('    $ deploy exec sequential');
    console.log('    $ deploy exec async');
    console.log();
  });

program.parse(process.argv);
```
为了方便一些文件的操作，还引入了[shell.js](https://github.com/arturadib/shelljs)。shelljs提供了跨平台的shell 命令，可以很方便的开发命令行工具。

```javascript
require('shelljs/global');

if (!which('git')) {
  echo('Sorry, this script requires git');
  exit(1);
}

// Copy files to release dir
mkdir('-p', 'out/Release');
cp('-R', 'stuff/*', 'out/Release');
```

**Comment by mobframe** [comment]
意见如下（主要参考ror）：
1.是不是可以加上 test 和 benchmark 两个命令，前一个跑单测用例，后一个测qps
2 run命令可否和ror的server 命令兼容下， 即设置run的alias 为 server . lark run == lark server 
3 ror 中有一个-e 参数可以切换运行环境，这个可参考 -e production|development
4 提供了 generate 命令是不是也可以提供destroy 命令(和ror一致).有时候误操作gen了错误的东西，手工删挺麻烦的。

**Comment by demohi** [comment]
#30

**Comment by zezhou** [comment]
已补充到wiki https://github.com/larkjs/lark/wiki/%E5%91%BD%E4%BB%A4%E8%A1%8C%E4%BD%BF%E7%94%A8

**Comment by demohi** [comment]
:+1:
