### ISSUE TITLE
内置支持 promise 的http, promisify

### ISSUE THREAD

**Issue by mobframe** [larkjs/lark#32]

**Comment by demohi** [comment]
有 koa、co开发小组成员维护的[thenify](https://github.com/thenables/thenify)质量比较有保证，同时目前还很活跃，因为他们也想为 co 社区多提供一些工具。

lark 的 promisify 会基于 thenify开发。

**Comment by mobframe** [comment]
看着很不错

**Comment by demohi** [comment]
#45
