### ISSUE TITLE
增加模版引擎支持

### ISSUE THREAD

**Issue by demohi** [larkjs/lark#33]
默认支持 ejs

**Comment by demohi** [comment]
基于 [koa-views](https://github.com/queckezz/koa-views)  开发，这个基于官方 co-views，算是有官方支持。

**Comment by demohi** [comment]
目前[ejs](https://github.com/mde/ejs)的代码在--harmony 下有 bug，无法运行。原因是变量的多次声明。已经提了 pr，等待被 merge

**Comment by demohi** [comment]
koa-views 目前由于目录问题，不能直接在 lark 中使用，已经提了 [pr](https://github.com/queckezz/koa-views/pull/29)，不知道会不会被 merge。

如果官方不打算 merge，我会fork 过来，把问题修复后，编程 lark-views

**Comment by demohi** [comment]
koa-views 官方觉得作为一个 koa 中间件，没有必要添加这个功能。所以会基于 co-views 开发 lark-views

**Comment by zezhou** [comment]
没有看到 benchmark 不知道性能咋样

**Comment by demohi** [comment]
这个只是对各种模板引擎的简单封装，没有太多性能消耗。最底层是 tj 的consolidate.js，应该还好。

**Comment by demohi** [comment]
#48

**Comment by demohi** [comment]
Done
