### ISSUE TITLE
增加日志模块支持  

### ISSUE THREAD

**Issue by demohi** [larkjs/lark#34]
注意日志格式
以及存放位置

**Comment by demohi** [comment]
https://github.com/flatiron/winston

https://github.com/trentm/node-bunyan

这是star 最多的两个 log 模块，会从中选择一个

**Comment by zezhou** [comment]
另外koa 自己有 log的中间件https://github.com/koajs/logger
不选这个有什么原因么

**Comment by demohi** [comment]
winston 和 bunyan，于logger不同。

logger 只是一个简单的调试工具，用来打印请求日志到控制台

winston 和 bunyan 是用来打印日志到文件，更符合我们的需求。

**Comment by demohi** [comment]
对比了多个日志模块  winston、log4js、bunyan、tracer，最后选择了 tracer，这个简单好用，功能强大，扩展性好。开发者是个国人，沟通也方便。

https://github.com/baryon/tracer

**Comment by demohi** [comment]
参考了 ODP 的 log 模块，lark-log 的用法大概如下

```javascript
var Log = require('lark-log');
var colors = require('colors');

var config = {
    format : "{{timestamp}} <{{title}}> {{message}} (in {{file}}:{{line}})",
    dateformat : "HH:MM:ss.L",
    files: {
        debug: {
            path: 'debug.log',
            options:{
                flags: 'w',
                encoding: 'utf8',
                fd: null
            }
        }
    },
    filters : {
        trace : colors.magenta,
        debug : colors.blue,
        info : colors.green,
        warn : colors.yellow,
        error : [ colors.red, colors.bold ]
    }
};
var logger = new Log(config);
```

可以设置输出的格式   可以设置时间的格式    可以指定 level，打印到指定文件，并且可以设置 stream的格式。 另外还可以对输出内容进行格式化

**Comment by mobframe** [comment]
两个问题：

这个能默认配置成符合某个日志规范，不用设置format么 
color在这里有什么用处？DEBUG 模块已经有了带颜色输出到控制台的功能吧，如果是开发时调试用，应该用DEBUG而不是logger吧

**Comment by demohi** [comment]
1：有默认的 format，不设置即可使用
2：color只是一个锦上添花的功能，没有必须要添加。主要依赖的 tracer，本身提供这个功能

**Comment by demohi** [comment]
Done #52
