### ISSUE TITLE
lark cli 和 yo 结合

### ISSUE THREAD

**Issue by zezhou** [larkjs/lark#41]
yo 有 generate 代码的功能

$ yo angular:controller myController
$ yo angular:directive myDirective
$ yo angular:filter myFilter
$ yo angular:service myService

因此 lark g 功能是否可以不再重复造轮子，而是做成 yo generate命令的一个alias. 如:

lark g controller myController == yo controller myController

**Comment by demohi** [comment]
这样会不会增加用户的使用成本
现在用户只需要安装 lark 即可使用 generate

改成 yo，用户首先下载 yo  然后还需要下载 generator-lark 
感觉是有些麻烦

**Comment by mobframe** [comment]
那是不是可以这样，
lark 内置yo, 和generator-lark，相关命令核心用yo实现, lark alias yo 功能即可
用法不变, 改动对用户透明，同时对高级用户 yo 也可以用

**Comment by zezhou** [comment]
在 0.5 版里搞一下吧，把和 init, create 相关的迁移到 yeoman 里去，lark库也可以少一点代码

**Comment by demohi** [comment]
OK

**Comment by demohi** [comment]
# Lark.js generator 


> Yeoman generator for Lark.js - lets you quickly set up a project with sensible defaults and best practices.

## Usage

Install `generator-lark`:
```
npm install -g generator-lark
```

You can Skip this by pass an app name . Make a new directory, and `cd` into it.:
```
mkdir my-new-project && cd $_
```

Run `yo lark`, optionally passing an app name:
```
yo lark [app-name]
```

## Generators

Available generators:

* [lark](#app) (aka [lark:app](#app))
* [lark:controller](#controller)
* [lark:data](#dataService)
* [lark:page](#pageService)
* [lark:dao](#dao)

**Note: Generators are to be run from the root directory of your app.**

### App
Sets up a new Lark.js app, generating all the boilerplate you need to get started. 

Example:
```bash
yo lark
```

### Controller
Generate controller file

Example:
```bash
yo lark:controller user  # create controllers/user/index.js
yo lark:controller user/  # create controllers/user/index.js
yo lark:controller user/create.js  # create controllers/user/create.js
```

### DataService
Generate dataService file

Example:
```bash
yo lark:data user.js  # create models/dataService/user.js
```

### PageService
Generate pageService file

Example:
```bash
yo lark:page user.js  # create models/pageService/user.js
```

### Dao
Generate dao file

Example:
```bash
yo lark:dao user.js  # create models/dao/user.js
```

**Comment by demohi** [comment]
https://github.com/larkjs/generator-lark   Done
