### ISSUE TITLE
命令行lark没有任何输出

### ISSUE THREAD

**Issue by viRingbells** [larkjs/lark#62]
直接使用命令`lark`后，没有任何输出，无法知道该命令执行了什么操作：
![image](https://cloud.githubusercontent.com/assets/6166326/5970764/d46d9d6a-a872-11e4-819c-e2c3845c3d23.png)
期望输出`lark -help`的结果

**Comment by demohi** [comment]
0.6 版本提供

**Comment by zezhou** [comment]
Done.
https://github.com/larkjs/lark/pull/73
