### ISSUE TITLE
编写 how to contribute 

### ISSUE THREAD

**Issue by demohi** [larkjs/lark#64]

**Comment by mobframe** [comment]
https://github.com/larkjs/lark/wiki/%E6%80%8E%E6%A0%B7%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81

**Comment by zezhou** [comment]
done, @luxiaoyan  review 下

**Comment by demohi** [comment]
:+1:

**Comment by luxiaoyan** [comment]
没问题
