### ISSUE TITLE
通用错误处理机制

### ISSUE THREAD

**Issue by zezhou** [larkjs/lark#86]

**Comment by viRingbells** [comment]
1：Lark中已经有对错误的处理方案，会在this.throw(err, statusCode)后对应的处理
2：如果需要增加对错误的自定义处理模块，则目前Lark工程的目录结构中没有对应的位置，需要增加一个，因此需要再讨论一下。

**Comment by zezhou** [comment]
这个会打到日志里么？会打到那个日志？

**Comment by viRingbells** [comment]
会有node.log，我这边加上了this.log.error打到错误日志里模块，等会儿pr
